language: ruby
rvm:
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - rbx-3.9
script: "bundle exec rspec"
notifications:
  email:
    recipients:
      - kigster@gmail.com
    on_success: never
    on_failure: always
